### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by wangxinbio** [maxplanck-ie/HiCAssembler#11]
Hi 
When I run the HiCAssembler, I got an error like below. How can I fix it ?

Traceback (most recent call last):
  File "/home/xw/sofware/HiC/bin/assemble", line 312, in <module>
    main(args)
  File "/home/xw/sofware/HiC/bin/assemble", line 308, in main
    chain_file=args.outFolder + "/liftover.chain")
  File "/home/xw/sofware/HiC/bin/assemble", line 218, in save_fasta
    assert(next_contig['start'] - end >= 0)
AssertionError

**Comment by fidelram** [comment]
For some reason the coordinates of a contig are not correct. How are you
calling hicassembler?

**Comment by wangxinbio** [comment]
@fidelram 
command is below:
assemble -m ctg_10kb_corrected.h5 -o ctg_10kb_corrected_default -f ctg_ident_0.99_cov_0.97_pilon.fasta

**Comment by ItokawaK** [comment]
I encountered the same issue. 
I commented out the lines including assert function and the run finished normally.
The obtained result looked fine at a glance, but I wonder whether there is any serious problem with this override.

**Comment by xuxiaoman0212** [comment]
I got the same error.

Hi fidel, how can I fix it? @fidelram 

Thanks for your help.
