### ISSUE TITLE
Problem with cooler version

### ISSUE THREAD

**Issue by nadegeguiglielmoni** [maxplanck-ie/HiCAssembler#13]
Hello, 

When I try to install the program, I encounter the following error : 

Collecting scandir; python_version < "3.5" (from pathlib2>=2.2.0; python_version < "3.6"->pytest>=2.8.1->HiCAssembler)
ERROR: hicmatrix 7 has requirement cooler==0.8.2, but you'll have cooler 0.8.5 which is incompatible.
ERROR: hicexplorer 2.2.1.1 has requirement cooler==0.8.2, but you'll have cooler 0.8.5 which is incompatible.

As a result, the program is not properly installed and cannot import HiCMatrix.

**Comment by vivekbhr** [comment]
You can either downgrade your cooler on your main env, or create a new [conda env](https://conda.io/en/latest) with the downgraded version.

```
conda create -n hicex -c bioconda -c conda-forge hicexplorer
conda activate hicex # or source activate, depending on conda version
pip install HiCAssembler
```

**Comment by francicco** [comment]
There are incompatible versions among packages. 
`hicexplorer` needs `Python3`
`HiCAssembler` needs `Python2`
`hic2cool` needs `cooler>=0.8.3` and Python3
but `HiCAssembler` wants `cooler==0.8.2`

If I try to install `hic2cool` at first using `Python3` and then `HiCAssembler` I get the same problem @nadegeguiglielmoni is facing and `assemble` don't work.

I get:

```
Traceback (most recent call last):
  File "/home/fc464/software/HiCAssembler/bin/assemble", line 11, in <module>
    import hicassembler.HiCAssembler as HiCAssembler
  File "/home/fc464/software/HiCAssembler/lib/python3.6/site-packages/hicassembler/HiCAssembler.py", line 226
    print self.N50
             ^
SyntaxError: Missing parentheses in call to 'print'
```
and

```
Traceback (most recent call last):
  File "/home/fc464/software/HiCAssembler/bin/assemble", line 11, in <module>
    import hicassembler.HiCAssembler as HiCAssembler
  File "/home/fc464/software/HiCAssembler/lib/python3.6/site-packages/hicassembler/HiCAssembler.py", line 346
    for node, degree in sorted(node_degree_mst.iteritems(), key=lambda (k, v): v, reverse=True):
```

I think these are issues due to different python versions.

I can't use conda, for some reason. I'm kind of stuck

@vivekbhr, any idea how to solve this?

Thanks
F

**Comment by fidelram** [comment]
@francicco The new 2to3 branch should solve the issue.

**Comment by nadegeguiglielmoni** [comment]
I am going to try the 2to3 branch because the previous solution did not work for me.
