### ISSUE TITLE
Assemble self.N50 Error 

### ISSUE THREAD

**Issue by francicco** [maxplanck-ie/HiCAssembler#14]
Hi,

I'm running `assemble` using this command line:

```
assemble -m hic_corrected.h5 -o ./assembly_output \
                --min_scaffold_length 100000 --bin_size 5000 --misassembly_zscore_threshold -1.0 \
                --num_iterations 3 --num_processors $THREADS
```
But I'm getting this

```
Traceback (most recent call last):
  File "/home/fc464/software/hicexplorer/bin/assemble", line 11, in <module>
    import hicassembler.HiCAssembler as HiCAssembler
  File "/home/fc464/software/hicexplorer/lib/python3.6/site-packages/hicassembler/HiCAssembler.py", line 226
    print self.N50
             ^
SyntaxError: Missing parentheses in call to 'print'
```

Anyway I could fix this?
Thanks
F

**Comment by francicco** [comment]
Apparently 

> HiCExplorer does no longer support Python 2. This dependency issue needs to be solved by HiCAssembler

Need to find another HiC assembler...

**Comment by xinl22** [comment]
@francicco Hi, have you fixed this issue?

**Comment by fidelram** [comment]
I had made some progress with a python3 version of hicassembler. The code is in the https://github.com/maxplanck-ie/HiCAssembler/tree/2to3 branch for those who wants to try it.

I still see some errors in the doctests that need to be investigated.
