### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by dominik-handler** [maxplanck-ie/HiCAssembler#16]
Hi, 
I saw that you have the branch 2to3 to migrate HiCAssembler to python 3. As it is getting quite difficult to install all dependencies for python 2.7 I wanted to try this branch. 
First of all I ran into an issue while installing this version:
`error in HiS Assembler setup command: "values of 'package_data' dict" must be a list of strings (got '*.txt')`

Also, before I invest time in testing HiCAssembler in python 3, is it fully functional yet?

All the best and thank you,
Dominik

**Comment by xuzhougeng** [comment]
I solve this problem by the following step

```
git clone https://github.com/maxplanck-ie/HiCAssembler.git
cd HiCAssembler/
git branch 2to3
```

and I edit the setup.py, and commment the the following line

```
#package_data={'': '*.txt'},
```

then I install this package locally

```bash
cd ..
pip install ./HiCAssembler/
```

**Comment by EarlyEvol** [comment]
xuzhougeng's fix resolves the first issue (same as dominik) but a new python 2>3 version issue remains:
 ```
Traceback (most recent call last):
  File "/home/u14/earlm1/miniconda3/envs/hic/bin/assemble", line 11, in <module>
    import hicassembler.HiCAssembler as HiCAssembler
  File "/home/u14/earlm1/miniconda3/envs/hic/lib/python3.6/site-packages/hicassembler/HiCAssembler.py", line 226
    print self.N50
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.N50)?
```
xuzhougeng,
Did you encounter the same error, or do I have a problem pulling the correct version of HiCAssembler.py?
I started from a clean miniconda3 env, installed HiCExplorer, then did your 2to3 HicAssembler install instructions.

Earl

**Comment by EarlyEvol** [comment]
Ahh needed a different command to pull the correct branch:
```git checkout -b 2to3 --track origin/2to3```
Don't understand git at all, but it worked.  
(still needed the setup.py edit)

**Comment by yuzhenpeng** [comment]
> 

I also get the same errors. could you please give me more help.

**Comment by yuzhenpeng** [comment]
It seems that import hicexplorer.HiCMatrix as HiCMatrix should be changed to import hicmatrix.HiCMatrix as HiCMatrix. #21
