### ISSUE TITLE
Conflict with Hi-CExplorer

### ISSUE THREAD

**Issue by karimi81** [maxplanck-ie/HiCAssembler#22]
I tried to install the HiCAssembler according to the instruction provided by developers, but there is a conflict between the version of hicexplorer (and also cooler) and  HiCAssembler. Whereas Hicexplorer uses python 3 to install packages, the HiCAssembler is based on python 2.7. After using python 3 to install HiCAssembler, I faced with these issues:
Traceback (most recent call last):
  File "/home/karimi81/hic-assembler/env_HiCAssembler_p37/bin/assemble", line 11, in <module>
    import hicassembler.HiCAssembler as HiCAssembler
  File "/home/karimi81/hic-assembler/env_HiCAssembler_p37/lib/python3.7/site-packages/hicassembler/HiCAssembler.py", line 226
    print self.N50
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.N50)?

I would be appreciated if any one can guide me to find out a way to install the software.

**Comment by ostueker** [comment]
The `setup.py` should clearly state that it requires (End of Life) Python 2 and is not compatible with Python 3.

Or even better, the devs could release a version that is actually compatible with a Python version that is still supported.
Issue #16 suggests that the branch 2to3 would actually work.

**Comment by yuzhenpeng** [comment]
Hi, I modified the fill followed #16 . But still some erros.
`
Traceback (most recent call last):
  File "./HiCAssembler-2to3/bin/assemble", line 11, in <module>
    import hicassembler.HiCAssembler as HiCAssembler
  File "/root/data1/yuzhenpeng2021/miniconda3/envs/HiCAssembler/lib/python3.8/site-packages/hicassembler/HiCAssembler.py", line 226
    print self.N50
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.N50)?

`

**Comment by yuzhenpeng** [comment]
It seems that import hicexplorer.HiCMatrix as HiCMatrix should be changed to import hicmatrix.HiCMatrix as HiCMatrix. #21
