### ISSUE TITLE
misassembly correction

### ISSUE THREAD

**Issue by yongyiyu** [maxplanck-ie/HiCAssembler#7]
Hi Fidel，
      I have created a corrected Hi-C matrix in h5 format by HiCExporer，now an assertion error killed the assembly  while using the HiCAssembler.
      " Traceback (most recent call last):
  File "/annoroad/data1/bioinfo/PMO/yangweifei/Hicassemble/py2/bin/assemble", line 312, in <module>
    main(args)
  File "/annoroad/data1/bioinfo/PMO/yangweifei/Hicassemble/py2/bin/assemble", line 308, in main
    chain_file=args.outFolder + "/liftover.chain")
  File "/annoroad/data1/bioinfo/PMO/yangweifei/Hicassemble/py2/bin/assemble", line 218, in save_fasta
    assert(next_contig['start'] - end >= 0)
AssertionError "
     I'm a little confused while checking the code of assemble. The misassembly correction of my data mybe    like the overlap of data. As the principle you described ,  "this means that a contig was split by the misassembly correction but was later joined together", the overlap of data isn't be considered , and  I think this kind of misassembly correction shouldn't be joined.

Best regards,
yongyi

**Comment by fidelram** [comment]
To be clear, did you run the misassembly correction before?

**Comment by yongyiyu** [comment]
Hi Fidel，
       I  ran the misassembly correction before  using the HiCAssembler. Now when test the he HiCAssembler with the Hi-C matrix ,that wasn't corrected，it worked successfully. So I think that the situation of the overlap may not be considered.

yongyi

**Comment by xuxiaoman0212** [comment]
Hi yongyi,

I got the same error, how did you solve it? @yongyiyu 

Thanks a lot!
