### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zhuangfjnu** [maxplanck-ie/HiCAssembler#9]
Hi Fidel,
After I installed HiCAssembler, I get this error
$assemble
Traceback (most recent call last):
  File "/share/bioinfo/anaconda3/bin/assemble", line 11, in <module>
    import hicassembler.HiCAssembler as HiCAssembler
  File "/share/bioinfo/anaconda3/lib/python3.6/site-packages/hicassembler/HiCAssembler.py", line 346
    for node, degree in sorted(node_degree_mst.iteritems(), key=lambda (k, v): v, reverse=True):
                                                                       ^
SyntaxError: invalid syntax

Could you give some suggestion about how to fix it ?

Thanks,
Zhen

**Comment by fidelram** [comment]
Try with python 2

Fidel Ramírez
